version: '3'

services:
  lab4_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nnik1320
      POSTGRES_DB: ntv
    ports:
      - "6050:5432"
    volumes:
      - lab4_volume1:/var/lib/postgresql/data


volumes:
  lab4_volume1: