server:
  port: 21412
  servlet:
    context-path: /
    session:
      timeout: 600s


bot:
  name: NTV
  token: 6116759525:AAGK8tzJijJbOLR5iGArE5c-rhHa4wVpyXg

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: nnik1320
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss